default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
  - repo: local
    hooks:
      - id: ruff
        name: ruff (linter)
        entry: just ruff-fix
        language: system
        types: [python]
      - id: black
        name: black
        entry: just black
        language: system
        types: [python]
